variables:
      MYSQL_DATABASE: "Rfam"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_USER: "rfamro"
      MYSQL_PASSWORD: ""
      MYSQL_HOST: "mysql-rfam-public.ebi.ac.uk"
      MYSQL_PORT: "4497"
      out_data: ""

default:
  image: python:latest  

workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /-draft$/
      when: never
    - if: '$CI_PIPELINE_SOURCE == "push"'  


stages:
  - test1
  - test2

test1:
  stage: test1
  #when: manual
  #allow_failure: true
  services:
    - mysql:5.7
  script:
    - apt-get update && apt-get install -y git curl libmcrypt-dev default-mysql-client
    - echo "$(<sql/1.sql)" | mysql -u "$MYSQL_USER" -h "${MYSQL_HOST}" --port "${MYSQL_PORT}" --database "${MYSQL_DATABASE}"  
  environment:
    name: test 1.sql
  only:
    refs:
      - main
    changes:
      - "sql/1.sql"


test2:
  stage: test2
  #when: manual
  #allow_failure: true
  services:
    - mysql:5.7
  script:
    - apt-get update && apt-get install -y git curl libmcrypt-dev default-mysql-client 
    - echo "$(<sql/2.sql)" | mysql -u "$MYSQL_USER" -h "${MYSQL_HOST}" --port "${MYSQL_PORT}" --database "${MYSQL_DATABASE}" 

  environment:
    name: test 2.sql
  only:
    refs:
      - main
    changes:
      - "sql/2.sql"
